"""Module contains names of methods used in Imputer Classes."""

DEFAULT = "default"
DEFAULT_PRED = "default predictive"
DEFAULT_UNIVAR = "default univariate"
DEFAULT_TIME = "default time"
MEAN = "mean"
MEDIAN = "median"
MODE = "mode"
RANDOM = "random"
NORM = "norm"
CATEGORICAL = "categorical"
INTERPOLATE = "interpolate"
LOCF = "locf"
NOCB = "nocb"
LS = "least squares"
BINARY_LOGISTIC = "binary logistic"
MULTI_LOGISTIC = "multinomial logistic"
STOCHASTIC = "stochastic"
BAYESIAN_LS = "bayesian least squares"
BAYESIAN_BINARY_LOGISTIC = "bayesian binary logistic"
PMM = "pmm"
LRD = "lrd"
NONE = "none"
NORM_UNIT_VARIANCE = 'normal unit variance'
